extends RefCounted
class_name SanguoshaCardCatalog

const STANDARD_CARD_PACK_ID := "standard_108"
const CARD_BACK := "res://assets/images/sanguosha/cards/card_back.png"

const STANDARD_108_CARDS := [
	{"template_id": "std_001", "card_key": "peach_garden", "name": "桃园结义", "suit": "heart", "rank": "A", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "peach_garden", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_001_heart_a_peach_garden.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_002", "card_key": "arrow_barrage", "name": "万箭齐发", "suit": "heart", "rank": "A", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "arrow_barrage", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_002_heart_a_arrow_barrage.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_003", "card_key": "dodge", "name": "闪", "suit": "heart", "rank": "2", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_003_heart_2_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_004", "card_key": "dodge", "name": "闪", "suit": "heart", "rank": "2", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_004_heart_2_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_005", "card_key": "peach", "name": "桃", "suit": "heart", "rank": "3", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_005_heart_3_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_006", "card_key": "harvest", "name": "五谷丰登", "suit": "heart", "rank": "3", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "harvest", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_006_heart_3_harvest.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_007", "card_key": "peach", "name": "桃", "suit": "heart", "rank": "4", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_007_heart_4_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_008", "card_key": "harvest", "name": "五谷丰登", "suit": "heart", "rank": "4", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "harvest", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_008_heart_4_harvest.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_009", "card_key": "qilin_bow", "name": "麒麟弓", "suit": "heart", "rank": "5", "copy_index": 1, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_009_heart_5_qilin_bow.png", "asset_format": "png", "metadata": {"range": 5}},
	{"template_id": "std_010", "card_key": "red_hare", "name": "赤兔", "suit": "heart", "rank": "5", "copy_index": 2, "type": "equip", "subtype": "attack_horse", "effect_key": "attack_horse", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_010_heart_5_red_hare.png", "asset_format": "png", "metadata": {"distance_to_others_delta": -1}},
	{"template_id": "std_011", "card_key": "peach", "name": "桃", "suit": "heart", "rank": "6", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_011_heart_6_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_012", "card_key": "indulgence", "name": "乐不思蜀", "suit": "heart", "rank": "6", "copy_index": 2, "type": "trick", "subtype": "delay_trick", "effect_key": "indulgence", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_012_heart_6_indulgence.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_013", "card_key": "peach", "name": "桃", "suit": "heart", "rank": "7", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_013_heart_7_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_014", "card_key": "draw_two", "name": "无中生有", "suit": "heart", "rank": "7", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "draw_two", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_014_heart_7_draw_two.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_015", "card_key": "peach", "name": "桃", "suit": "heart", "rank": "8", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_015_heart_8_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_016", "card_key": "draw_two", "name": "无中生有", "suit": "heart", "rank": "8", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "draw_two", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_016_heart_8_draw_two.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_017", "card_key": "peach", "name": "桃", "suit": "heart", "rank": "9", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_017_heart_9_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_018", "card_key": "draw_two", "name": "无中生有", "suit": "heart", "rank": "9", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "draw_two", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_018_heart_9_draw_two.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_019", "card_key": "slash", "name": "杀", "suit": "heart", "rank": "10", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_019_heart_10_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_020", "card_key": "slash", "name": "杀", "suit": "heart", "rank": "10", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_020_heart_10_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_021", "card_key": "slash", "name": "杀", "suit": "heart", "rank": "J", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_021_heart_j_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_022", "card_key": "draw_two", "name": "无中生有", "suit": "heart", "rank": "J", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "draw_two", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_022_heart_j_draw_two.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_023", "card_key": "peach", "name": "桃", "suit": "heart", "rank": "Q", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_023_heart_q_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_024", "card_key": "dismantle", "name": "过河拆桥", "suit": "heart", "rank": "Q", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "dismantle", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_024_heart_q_dismantle.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_025", "card_key": "lightning", "name": "闪电", "suit": "heart", "rank": "Q", "copy_index": 3, "type": "trick", "subtype": "delay_trick", "effect_key": "lightning", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_025_heart_q_lightning.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_026", "card_key": "dodge", "name": "闪", "suit": "heart", "rank": "K", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_026_heart_k_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_027", "card_key": "zhuahuang_feidian", "name": "爪黄飞电", "suit": "heart", "rank": "K", "copy_index": 2, "type": "equip", "subtype": "defense_horse", "effect_key": "defense_horse", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_027_heart_k_zhuahuang_feidian.png", "asset_format": "png", "metadata": {"distance_from_others_delta": 1}},
	{"template_id": "std_028", "card_key": "duel", "name": "决斗", "suit": "spade", "rank": "A", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "duel", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_028_spade_a_duel.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_029", "card_key": "lightning", "name": "闪电", "suit": "spade", "rank": "A", "copy_index": 2, "type": "trick", "subtype": "delay_trick", "effect_key": "lightning", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_029_spade_a_lightning.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_030", "card_key": "double_swords", "name": "雌雄双股剑", "suit": "spade", "rank": "2", "copy_index": 1, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_030_spade_2_double_swords.png", "asset_format": "png", "metadata": {"range": 2}},
	{"template_id": "std_031", "card_key": "eight_diagram", "name": "八卦阵", "suit": "spade", "rank": "2", "copy_index": 2, "type": "equip", "subtype": "armor", "effect_key": "armor", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_031_spade_2_eight_diagram.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_032", "card_key": "ice_sword", "name": "寒冰剑", "suit": "spade", "rank": "2", "copy_index": 3, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_032_spade_2_ice_sword.png", "asset_format": "png", "metadata": {"range": 2}},
	{"template_id": "std_033", "card_key": "dismantle", "name": "过河拆桥", "suit": "spade", "rank": "3", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "dismantle", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_033_spade_3_dismantle.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_034", "card_key": "snatch", "name": "顺手牵羊", "suit": "spade", "rank": "3", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "snatch", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_034_spade_3_snatch.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_035", "card_key": "dismantle", "name": "过河拆桥", "suit": "spade", "rank": "4", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "dismantle", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_035_spade_4_dismantle.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_036", "card_key": "snatch", "name": "顺手牵羊", "suit": "spade", "rank": "4", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "snatch", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_036_spade_4_snatch.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_037", "card_key": "green_dragon_blade", "name": "青龙偃月刀", "suit": "spade", "rank": "5", "copy_index": 1, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_037_spade_5_green_dragon_blade.png", "asset_format": "png", "metadata": {"range": 3}},
	{"template_id": "std_038", "card_key": "jueying", "name": "绝影", "suit": "spade", "rank": "5", "copy_index": 2, "type": "equip", "subtype": "defense_horse", "effect_key": "defense_horse", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_038_spade_5_jueying.png", "asset_format": "png", "metadata": {"distance_from_others_delta": 1}},
	{"template_id": "std_039", "card_key": "indulgence", "name": "乐不思蜀", "suit": "spade", "rank": "6", "copy_index": 1, "type": "trick", "subtype": "delay_trick", "effect_key": "indulgence", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_039_spade_6_indulgence.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_040", "card_key": "blue_steel_blade", "name": "青釭剑", "suit": "spade", "rank": "6", "copy_index": 2, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_040_spade_6_blue_steel_blade.png", "asset_format": "png", "metadata": {"range": 2}},
	{"template_id": "std_041", "card_key": "slash", "name": "杀", "suit": "spade", "rank": "7", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_041_spade_7_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_042", "card_key": "barbarian_assault", "name": "南蛮入侵", "suit": "spade", "rank": "7", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "barbarian_assault", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_042_spade_7_barbarian_assault.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_043", "card_key": "slash", "name": "杀", "suit": "spade", "rank": "8", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_043_spade_8_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_044", "card_key": "slash", "name": "杀", "suit": "spade", "rank": "8", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_044_spade_8_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_045", "card_key": "slash", "name": "杀", "suit": "spade", "rank": "9", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_045_spade_9_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_046", "card_key": "slash", "name": "杀", "suit": "spade", "rank": "9", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_046_spade_9_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_047", "card_key": "slash", "name": "杀", "suit": "spade", "rank": "10", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_047_spade_10_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_048", "card_key": "slash", "name": "杀", "suit": "spade", "rank": "10", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_048_spade_10_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_049", "card_key": "snatch", "name": "顺手牵羊", "suit": "spade", "rank": "J", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "snatch", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_049_spade_j_snatch.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_050", "card_key": "negate", "name": "无懈可击", "suit": "spade", "rank": "J", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "negate", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_050_spade_j_negate.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_051", "card_key": "dismantle", "name": "过河拆桥", "suit": "spade", "rank": "Q", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "dismantle", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_051_spade_q_dismantle.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_052", "card_key": "serpent_spear", "name": "丈八蛇矛", "suit": "spade", "rank": "Q", "copy_index": 2, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_052_spade_q_serpent_spear.png", "asset_format": "png", "metadata": {"range": 3}},
	{"template_id": "std_053", "card_key": "barbarian_assault", "name": "南蛮入侵", "suit": "spade", "rank": "K", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "barbarian_assault", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_053_spade_k_barbarian_assault.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_054", "card_key": "dayuan", "name": "大宛", "suit": "spade", "rank": "K", "copy_index": 2, "type": "equip", "subtype": "attack_horse", "effect_key": "attack_horse", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_054_spade_k_dayuan.png", "asset_format": "png", "metadata": {"distance_to_others_delta": -1}},
	{"template_id": "std_055", "card_key": "crossbow", "name": "诸葛连弩", "suit": "diamond", "rank": "A", "copy_index": 1, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_055_diamond_a_crossbow.png", "asset_format": "png", "metadata": {"range": 1}},
	{"template_id": "std_056", "card_key": "duel", "name": "决斗", "suit": "diamond", "rank": "A", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "duel", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_056_diamond_a_duel.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_057", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "2", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_057_diamond_2_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_058", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "2", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_058_diamond_2_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_059", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "3", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_059_diamond_3_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_060", "card_key": "snatch", "name": "顺手牵羊", "suit": "diamond", "rank": "3", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "snatch", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_060_diamond_3_snatch.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_061", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "4", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_061_diamond_4_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_062", "card_key": "snatch", "name": "顺手牵羊", "suit": "diamond", "rank": "4", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "snatch", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_062_diamond_4_snatch.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_063", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "5", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_063_diamond_5_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_064", "card_key": "rock_cleaving_axe", "name": "贯石斧", "suit": "diamond", "rank": "5", "copy_index": 2, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_064_diamond_5_rock_cleaving_axe.png", "asset_format": "png", "metadata": {"range": 3}},
	{"template_id": "std_065", "card_key": "slash", "name": "杀", "suit": "diamond", "rank": "6", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_065_diamond_6_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_066", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "6", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_066_diamond_6_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_067", "card_key": "slash", "name": "杀", "suit": "diamond", "rank": "7", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_067_diamond_7_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_068", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "7", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_068_diamond_7_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_069", "card_key": "slash", "name": "杀", "suit": "diamond", "rank": "8", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_069_diamond_8_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_070", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "8", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_070_diamond_8_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_071", "card_key": "slash", "name": "杀", "suit": "diamond", "rank": "9", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_071_diamond_9_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_072", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "9", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_072_diamond_9_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_073", "card_key": "slash", "name": "杀", "suit": "diamond", "rank": "10", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_073_diamond_10_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_074", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "10", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_074_diamond_10_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_075", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "J", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_075_diamond_j_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_076", "card_key": "dodge", "name": "闪", "suit": "diamond", "rank": "J", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "dodge", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_076_diamond_j_dodge.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_077", "card_key": "peach", "name": "桃", "suit": "diamond", "rank": "Q", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "peach", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_077_diamond_q_peach.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_078", "card_key": "halberd", "name": "方天画戟", "suit": "diamond", "rank": "Q", "copy_index": 2, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_078_diamond_q_halberd.png", "asset_format": "png", "metadata": {"range": 4}},
	{"template_id": "std_079", "card_key": "negate", "name": "无懈可击", "suit": "diamond", "rank": "Q", "copy_index": 3, "type": "trick", "subtype": "non_delay_trick", "effect_key": "negate", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_079_diamond_q_negate.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_080", "card_key": "slash", "name": "杀", "suit": "diamond", "rank": "K", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_080_diamond_k_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_081", "card_key": "zixing", "name": "紫骍", "suit": "diamond", "rank": "K", "copy_index": 2, "type": "equip", "subtype": "attack_horse", "effect_key": "attack_horse", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_081_diamond_k_zixing.png", "asset_format": "png", "metadata": {"distance_to_others_delta": -1}},
	{"template_id": "std_082", "card_key": "duel", "name": "决斗", "suit": "club", "rank": "A", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "duel", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_082_club_a_duel.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_083", "card_key": "crossbow", "name": "诸葛连弩", "suit": "club", "rank": "A", "copy_index": 2, "type": "equip", "subtype": "weapon", "effect_key": "weapon", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_083_club_a_crossbow.png", "asset_format": "png", "metadata": {"range": 1}},
	{"template_id": "std_084", "card_key": "slash", "name": "杀", "suit": "club", "rank": "2", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_084_club_2_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_085", "card_key": "eight_diagram", "name": "八卦阵", "suit": "club", "rank": "2", "copy_index": 2, "type": "equip", "subtype": "armor", "effect_key": "armor", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_085_club_2_eight_diagram.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_086", "card_key": "renwang_shield", "name": "仁王盾", "suit": "club", "rank": "2", "copy_index": 3, "type": "equip", "subtype": "armor", "effect_key": "armor", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_086_club_2_renwang_shield.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_087", "card_key": "slash", "name": "杀", "suit": "club", "rank": "3", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_087_club_3_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_088", "card_key": "dismantle", "name": "过河拆桥", "suit": "club", "rank": "3", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "dismantle", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_088_club_3_dismantle.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_089", "card_key": "slash", "name": "杀", "suit": "club", "rank": "4", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_089_club_4_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_090", "card_key": "dismantle", "name": "过河拆桥", "suit": "club", "rank": "4", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "dismantle", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_090_club_4_dismantle.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_091", "card_key": "slash", "name": "杀", "suit": "club", "rank": "5", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_091_club_5_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_092", "card_key": "dilu", "name": "的卢", "suit": "club", "rank": "5", "copy_index": 2, "type": "equip", "subtype": "defense_horse", "effect_key": "defense_horse", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_092_club_5_dilu.png", "asset_format": "png", "metadata": {"distance_from_others_delta": 1}},
	{"template_id": "std_093", "card_key": "slash", "name": "杀", "suit": "club", "rank": "6", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_093_club_6_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_094", "card_key": "indulgence", "name": "乐不思蜀", "suit": "club", "rank": "6", "copy_index": 2, "type": "trick", "subtype": "delay_trick", "effect_key": "indulgence", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_094_club_6_indulgence.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_095", "card_key": "slash", "name": "杀", "suit": "club", "rank": "7", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_095_club_7_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_096", "card_key": "barbarian_assault", "name": "南蛮入侵", "suit": "club", "rank": "7", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "barbarian_assault", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_096_club_7_barbarian_assault.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_097", "card_key": "slash", "name": "杀", "suit": "club", "rank": "8", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_097_club_8_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_098", "card_key": "slash", "name": "杀", "suit": "club", "rank": "8", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_098_club_8_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_099", "card_key": "slash", "name": "杀", "suit": "club", "rank": "9", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_099_club_9_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_100", "card_key": "slash", "name": "杀", "suit": "club", "rank": "9", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_100_club_9_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_101", "card_key": "slash", "name": "杀", "suit": "club", "rank": "10", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_101_club_10_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_102", "card_key": "slash", "name": "杀", "suit": "club", "rank": "10", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_102_club_10_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_103", "card_key": "slash", "name": "杀", "suit": "club", "rank": "J", "copy_index": 1, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_103_club_j_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_104", "card_key": "slash", "name": "杀", "suit": "club", "rank": "J", "copy_index": 2, "type": "basic", "subtype": "basic", "effect_key": "slash", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_104_club_j_slash.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_105", "card_key": "borrow_sword", "name": "借刀杀人", "suit": "club", "rank": "Q", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "borrow_sword", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_105_club_q_borrow_sword.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_106", "card_key": "negate", "name": "无懈可击", "suit": "club", "rank": "Q", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "negate", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_106_club_q_negate.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_107", "card_key": "borrow_sword", "name": "借刀杀人", "suit": "club", "rank": "K", "copy_index": 1, "type": "trick", "subtype": "non_delay_trick", "effect_key": "borrow_sword", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_107_club_k_borrow_sword.png", "asset_format": "png", "metadata": {}},
	{"template_id": "std_108", "card_key": "negate", "name": "无懈可击", "suit": "club", "rank": "K", "copy_index": 2, "type": "trick", "subtype": "non_delay_trick", "effect_key": "negate", "asset_path": "res://assets/images/sanguosha/cards/standard_108/std_108_club_k_negate.png", "asset_format": "png", "metadata": {}},
]


func cards(pack_id: String = STANDARD_CARD_PACK_ID) -> Array:
	if pack_id != STANDARD_CARD_PACK_ID:
		return []
	return STANDARD_108_CARDS.duplicate(true)


func card_count(pack_id: String = STANDARD_CARD_PACK_ID) -> int:
	return cards(pack_id).size()


func card_back_path() -> String:
	return CARD_BACK


func card_asset_path(template_id: String) -> String:
	for card_value in STANDARD_108_CARDS:
		var card: Dictionary = card_value
		if String(card.get("template_id", "")) == template_id:
			return String(card.get("asset_path", ""))
	return CARD_BACK


func counts_by_type() -> Dictionary:
	var result := {}
	for card_value in STANDARD_108_CARDS:
		var card: Dictionary = card_value
		var card_type := String(card.get("type", ""))
		result[card_type] = int(result.get(card_type, 0)) + 1
	return result


func counts_by_card_key() -> Dictionary:
	var result := {}
	for card_value in STANDARD_108_CARDS:
		var card: Dictionary = card_value
		var card_key := String(card.get("card_key", ""))
		result[card_key] = int(result.get(card_key, 0)) + 1
	return result
